FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production
COPY . .

FROM node:22-alpine
WORKDIR /app
COPY --from=build /app ./
EXPOSE 8080
ENV NODE_ENV=production
CMD [ "node", "server.js" ]
